"""Tests for the pure Python KMAG Saturn field model.

Validates against Fortran reference data generated by
fortran/kmag_test_driver.f and fortran/kmag_grid_driver.f.
"""

from __future__ import annotations

import math
import time as time_mod
from pathlib import Path

import numpy as np
import pytest
from numpy.testing import assert_allclose

from qp.fieldline.kmag_model import SaturnField, SaturnFieldConfig
from qp.fieldline.saturn_coords import (
    epoch_to_j2000,
    rotate_vector,
    sun_position,
)
from qp.fieldline._numba_kernels import (
    _internal_field as internal_field_jit,
    _is_inside_mp,
    _imf_penetration,
)
from qp.fieldline.tracer import (
    saturn_field_wrapper,
    trace_fieldline,
    trace_fieldline_bidirectional,
)

_TESTS_DIR = Path(__file__).parent

# ============================================================================
# Fortran reference data
# ============================================================================
# Generated by fortran/kmag_test_driver.f with:
#   epoch='j2000', BY_IMF=-0.2, BZ_IMF=0.1, Dp=0.017
# Columns: r, theta, phi, time, Br, Bt, Bp (all in nT, S3C spherical)

_FORTRAN_REF = np.array(
    [
        # r, theta, phi, time, Br, Bt, Bp
        [
            10.0,
            math.pi / 2,
            0.0,
            284040000.0,
            -0.503364112807452,
            14.3152384526582,
            0.0683099132980646,
        ],
        [
            10.0,
            math.pi / 2,
            math.pi / 2,
            284040000.0,
            0.153025803928079,
            15.3056175329177,
            -0.0680321550065982,
        ],
        [
            10.0,
            math.pi / 2,
            math.pi,
            284040000.0,
            0.0204985353072975,
            15.2790625966964,
            -0.0646574239813311,
        ],
        [
            5.0,
            math.pi / 2,
            0.0,
            284040000.0,
            -4.07277989308434,
            154.652969448065,
            0.0672435845024410,
        ],
        [
            15.0,
            math.pi / 2,
            0.0,
            284040000.0,
            -0.412129077190877,
            3.52293448894539,
            0.0704496560942486,
        ],
        [
            20.0,
            math.pi / 2,
            0.0,
            284040000.0,
            -0.481466756679434,
            1.76519296990686,
            0.0733653300498462,
        ],
        [
            10.0,
            math.pi / 4,
            0.0,
            284040000.0,
            36.0366259744926,
            13.5234922091965,
            -0.201274321432874,
        ],
        [
            5.0,
            0.1,
            0.0,
            284040000.0,
            355.862845260679,
            17.8411895660925,
            -0.165134442052834,
        ],
        [
            3.0,
            math.pi / 2,
            0.0,
            284040000.0,
            -29.8392430560131,
            758.381065469977,
            0.0670963896104847,
        ],
        # Different time (t=0)
        [
            10.0,
            math.pi / 2,
            0.0,
            0.0,
            1.90331556909706,
            15.2488224400427,
            -0.0570444221802118,
        ],
        # Zero IMF (separate config needed)
        # [10.0, math.pi/2, 0.0, 284040000.0, -0.569063555015154, 14.3620704556257, 0.00125799514315711],
        [
            10.0,
            math.pi / 3,
            math.pi / 4,
            284040000.0,
            27.5057889690965,
            15.9094714383106,
            -0.335632650188920,
        ],
    ]
)


# ============================================================================
# Coordinate transform tests
# ============================================================================


class TestCoordinateTransforms:
    """Tests for saturn_coords.py coordinate transformations."""

    def test_s3c_roundtrip(self):
        """S3C → KSM → S3C should be identity."""
        v = np.array([1.0, 2.0, 3.0])
        t = 284040000.0
        v_ksm = rotate_vector(v, "S3C", "KSM", t)
        v_back = rotate_vector(v_ksm, "KSM", "S3C", t)
        assert_allclose(v_back, v, atol=1e-12)

    def test_dis_roundtrip(self):
        """S3C → DIS → S3C should be identity."""
        v = np.array([5.0, -3.0, 7.0])
        t = 284040000.0
        v_dis = rotate_vector(v, "S3C", "DIS", t)
        v_back = rotate_vector(v_dis, "DIS", "S3C", t)
        assert_allclose(v_back, v, atol=1e-12)

    def test_kso_roundtrip(self):
        """S3C → KSO → S3C should be approximately identity.

        KSO axes aren't perfectly orthogonal (Zkso is independent of sun
        direction), so roundtrip has ~0.03% error. This matches the Fortran.
        """
        v = np.array([-2.0, 4.0, 1.0])
        t = 100000000.0
        v_kso = rotate_vector(v, "S3C", "KSO", t)
        v_back = rotate_vector(v_kso, "KSO", "S3C", t)
        assert_allclose(v_back, v, atol=1e-3)

    def test_sun_position_returns_finite(self):
        """sun_position should return finite values for valid times."""
        stheta, sphi, ztheta, zphi = sun_position(284040000.0)
        assert math.isfinite(stheta)
        assert math.isfinite(sphi)
        assert math.isfinite(ztheta)
        assert math.isfinite(zphi)

    def test_epoch_j2000_passthrough(self):
        """j2000 epoch should return time unchanged."""
        assert epoch_to_j2000(12345.0, "j2000") == 12345.0


# ============================================================================
# Magnetopause tests
# ============================================================================


class TestMagnetopause:
    """Tests for magnetopause boundary."""

    def test_subsolar_standoff(self):
        """Subsolar standoff with nominal pressure should be ~24.5 Rs."""
        r0 = 9.696 * 0.017 ** (-0.2351)
        assert _is_inside_mp(r0 - 1.0, r0 - 1.0, 0.017)
        assert not _is_inside_mp(r0 + 5.0, r0 + 5.0, 0.017)

    def test_origin_is_inside(self):
        """Origin should always be inside magnetopause."""
        assert _is_inside_mp(0.0, 0.0, 0.017)


# ============================================================================
# IMF penetration tests
# ============================================================================


class TestIMFPenetration:
    """Tests for IMF penetration through magnetopause."""

    def test_zero_imf(self):
        """Zero IMF should give zero penetration."""
        by, bz = _imf_penetration(0.0, 0.0)
        assert by == 0.0
        assert bz == 0.0

    def test_nonzero_imf(self):
        """Non-zero IMF should give non-zero penetration."""
        by_imf, bz_imf = -0.2, 0.1
        by, bz = _imf_penetration(by_imf, bz_imf)
        assert by != 0.0
        assert bz != 0.0
        assert abs(by) < abs(by_imf)
        assert abs(bz) < abs(bz_imf)


# ============================================================================
# Full field comparison against Fortran
# ============================================================================


class TestAgainstFortran:
    """Compare Python KMAG output against Fortran reference values."""

    @pytest.fixture
    def field(self):
        return SaturnField()

    @pytest.mark.parametrize(
        "row_idx",
        range(len(_FORTRAN_REF)),
        ids=[
            "10Rs_eq_phi0",
            "10Rs_eq_phipi2",
            "10Rs_eq_phipi",
            "5Rs_eq_phi0",
            "15Rs_eq_phi0",
            "20Rs_eq_phi0",
            "10Rs_45lat",
            "5Rs_pole",
            "3Rs_eq",
            "10Rs_eq_t0",
            "10Rs_th60_phi45",
        ],
    )
    def test_field_matches_fortran(self, field, row_idx):
        """Python field_s3c should match Fortran KMAG within 0.1%."""
        row = _FORTRAN_REF[row_idx]
        r, theta, phi, time = row[0], row[1], row[2], row[3]
        br_ref, bt_ref, bp_ref = row[4], row[5], row[6]

        br, bt, bp = field.field_s3c(r, theta, phi, time)

        # Use relative tolerance for components > 1 nT,
        # absolute tolerance for small components
        b_mag = math.sqrt(br_ref**2 + bt_ref**2 + bp_ref**2)

        assert_allclose(
            br,
            br_ref,
            rtol=1e-3,
            atol=0.01 * b_mag,
            err_msg=f"Br mismatch at r={r}, theta={theta:.3f}",
        )
        assert_allclose(
            bt,
            bt_ref,
            rtol=1e-3,
            atol=0.01 * b_mag,
            err_msg=f"Bt mismatch at r={r}, theta={theta:.3f}",
        )
        assert_allclose(
            bp,
            bp_ref,
            rtol=1e-3,
            atol=0.01 * b_mag,
            err_msg=f"Bp mismatch at r={r}, theta={theta:.3f}",
        )


# ============================================================================
# Internal field sanity checks
# ============================================================================


class TestInternalField:
    """Tests for the spherical harmonic internal field."""

    @pytest.fixture(scope="class")
    def coeffs(self):
        """Get normalized coefficients from a SaturnField instance."""
        field = SaturnField()
        return field._g, field._h, field._rec

    def test_equatorial_field_finite(self, coeffs):
        """Internal field at equator should be finite and small at large r."""
        g, h, rec = coeffs
        br, bt, bp = internal_field_jit(10.0, math.pi / 2, 0.0, g, h, rec, 3)
        assert all(math.isfinite(x) for x in (br, bt, bp))
        assert abs(bt) < 1.0

    def test_field_decreases_with_distance(self, coeffs):
        """Internal field should decrease with distance."""
        g, h, rec = coeffs
        _, bt_near, _ = internal_field_jit(3.0, math.pi / 2, 0.0, g, h, rec, 3)
        _, bt_far, _ = internal_field_jit(10.0, math.pi / 2, 0.0, g, h, rec, 3)
        assert abs(bt_near) > abs(bt_far)

    def test_polar_field_stronger(self, coeffs):
        """At the pole, Br should be stronger than at equator."""
        g, h, rec = coeffs
        br_pole, _, _ = internal_field_jit(5.0, 0.1, 0.0, g, h, rec, 3)
        br_eq, _, _ = internal_field_jit(5.0, math.pi / 2, 0.0, g, h, rec, 3)
        assert abs(br_pole) > abs(br_eq)


# ============================================================================
# 229-point grid comparison against Fortran
# ============================================================================


class TestExpandedFortranGrid:
    """Compare Python against 54 Fortran points covering Dp, IMF, near-MP, and edge cases."""

    @pytest.fixture(scope="class")
    def expanded_data(self):
        """Load expanded reference (10 cols: r, θ, φ, time, Dp, By, Bz, Br, Bt, Bp)."""
        path = _TESTS_DIR / "fortran_reference_params.txt"
        if not path.exists():
            pytest.skip("fortran_reference_params.txt not found")
        return np.loadtxt(path)

    def test_expanded_grid_loaded(self, expanded_data):
        """Expanded reference should have 54 rows and 10 columns."""
        assert expanded_data.shape[0] >= 50
        assert expanded_data.shape[1] == 10

    def test_all_expanded_points_match(self, expanded_data):
        """All expanded grid points should match Fortran within tolerance."""
        mismatches = []
        for i, row in enumerate(expanded_data):
            r, theta, phi, t = row[0], row[1], row[2], row[3]
            dp, by_imf, bz_imf = row[4], row[5], row[6]
            br_ref, bt_ref, bp_ref = row[7], row[8], row[9]
            b_mag = math.sqrt(br_ref**2 + bt_ref**2 + bp_ref**2)

            config = SaturnFieldConfig(dp=dp, by_imf=by_imf, bz_imf=bz_imf)
            field = SaturnField(config)
            br, bt, bp = field.field_s3c(r, theta, phi, t)

            tol = max(0.001 * b_mag, 0.1)
            if (
                abs(br - br_ref) > tol
                or abs(bt - bt_ref) > tol
                or abs(bp - bp_ref) > tol
            ):
                mismatches.append(
                    f"Row {i}: r={r}, Dp={dp}, By={by_imf}, Bz={bz_imf} "
                    f"Br: {br:.4f} vs {br_ref:.4f}, "
                    f"Bt: {bt:.4f} vs {bt_ref:.4f}"
                )
        assert not mismatches, (
            f"{len(mismatches)}/{len(expanded_data)} points failed:\n"
            + "\n".join(mismatches[:10])
        )


class TestFortranGrid:
    """Compare Python against 229 Fortran reference points covering r, theta, phi, time."""

    @pytest.fixture(scope="class")
    def grid_data(self):
        """Load the Fortran reference grid (7 columns: r, theta, phi, time, Br, Bt, Bp)."""
        path = _TESTS_DIR / "fortran_reference_grid.txt"
        if not path.exists():
            pytest.skip(
                "fortran_reference_grid.txt not found — run fortran/kmag_grid_driver"
            )
        return np.loadtxt(path)

    @pytest.fixture(scope="class")
    def field(self):
        return SaturnField()

    def test_grid_loaded(self, grid_data):
        """Reference grid should have 229 rows and 7 columns."""
        assert grid_data.shape[0] >= 200
        assert grid_data.shape[1] == 7

    def test_all_grid_points_match(self, field, grid_data):
        """All 229 grid points should match Fortran within 0.1% or 0.1 nT."""
        mismatches = []
        for i, row in enumerate(grid_data):
            r, theta, phi, t = row[0], row[1], row[2], row[3]
            br_ref, bt_ref, bp_ref = row[4], row[5], row[6]
            b_mag = math.sqrt(br_ref**2 + bt_ref**2 + bp_ref**2)

            br, bt, bp = field.field_s3c(r, theta, phi, t)

            tol = max(0.001 * b_mag, 0.1)  # 0.1% or 0.1 nT
            if (
                abs(br - br_ref) > tol
                or abs(bt - bt_ref) > tol
                or abs(bp - bp_ref) > tol
            ):
                mismatches.append(
                    f"Row {i}: r={r}, th={theta:.3f}, ph={phi:.3f} "
                    f"Br: {br:.4f} vs {br_ref:.4f}, "
                    f"Bt: {bt:.4f} vs {bt_ref:.4f}, "
                    f"Bp: {bp:.4f} vs {bp_ref:.4f}"
                )
        assert not mismatches, (
            f"{len(mismatches)}/{len(grid_data)} points failed:\n"
            + "\n".join(mismatches[:10])
        )

    def test_grid_relative_error_statistics(self, field, grid_data):
        """Median relative error across all grid points should be < 0.01%."""
        errors = []
        for row in grid_data:
            r, theta, phi, t = row[0], row[1], row[2], row[3]
            b_ref = np.array([row[4], row[5], row[6]])
            b_mag = np.linalg.norm(b_ref)
            if b_mag < 0.01:
                continue

            br, bt, bp = field.field_s3c(r, theta, phi, t)
            b_py = np.array([br, bt, bp])
            rel_err = np.linalg.norm(b_py - b_ref) / b_mag
            errors.append(rel_err)

        errors = np.array(errors)
        median_err = np.median(errors)
        max_err = np.max(errors)
        assert median_err < 1e-4, (
            f"Median relative error {median_err:.2e} exceeds 0.01%"
        )
        assert max_err < 0.01, f"Max relative error {max_err:.2e} exceeds 1%"


# ============================================================================
# Known physical limits
# ============================================================================


class TestKnownLimits:
    """Tests for physically expected limiting behavior."""

    def test_dipole_dominates_at_small_r(self):
        """At r=2 Rs, the total field should be dominated by the dipole (~2600 nT)."""
        field = SaturnField()
        _, bt, _ = field.field_s3c(2.0, math.pi / 2, 0.0, time=284040000.0)
        # Dipole B0z=21191, so at equator r=2: Bt ~ B0z/r^3 = 21191/8 ~ 2649 nT
        assert abs(bt) > 2000.0
        assert abs(bt) < 4000.0

    def test_field_weak_at_large_r(self):
        """At 25 Rs equator, total field should be < 5 nT."""
        field = SaturnField()
        br, bt, bp = field.field_s3c(25.0, math.pi / 2, 0.0, time=284040000.0)
        b_mag = math.sqrt(br**2 + bt**2 + bp**2)
        assert b_mag < 5.0

    def test_outside_magnetopause_only_imf(self):
        """Far outside the magnetopause, field should equal IMF penetration only."""
        # At r=100 Rs subsolar, well outside MP (~24 Rs)
        field = SaturnField()
        br, bt, bp = field.field_s3c(100.0, math.pi / 2, 0.0, time=284040000.0)
        b_mag = math.sqrt(br**2 + bt**2 + bp**2)
        # IMF penetration is very weak (~0.1 nT with default parameters)
        assert b_mag < 1.0

    def test_field_continuous_across_equator(self):
        """Field should be continuous across the equatorial plane."""
        field = SaturnField()
        t = 284040000.0
        # Just above and below equator
        _, bt_above, _ = field.field_s3c(10.0, math.pi / 2 - 0.01, 0.0, t)
        _, bt_below, _ = field.field_s3c(10.0, math.pi / 2 + 0.01, 0.0, t)
        # Should be very close (current sheet might cause some asymmetry)
        assert abs(bt_above - bt_below) / max(abs(bt_above), 0.1) < 0.1

    def test_axisymmetry_of_internal_field(self):
        """Internal field should be nearly axisymmetric (Saturn's H coefficients are zero)."""
        field = SaturnField()
        g, h, rec = field._g, field._h, field._rec
        results = []
        for phi in [0.0, math.pi / 2, math.pi, 3 * math.pi / 2]:
            br, bt, bp = internal_field_jit(5.0, math.pi / 3, phi, g, h, rec, 3)
            results.append((br, bt))
        br_vals = [r[0] for r in results]
        bt_vals = [r[1] for r in results]
        assert_allclose(br_vals, br_vals[0], atol=1e-10)
        assert_allclose(bt_vals, bt_vals[0], atol=1e-10)


# ============================================================================
# Field line tracing comparison
# ============================================================================


class TestFieldLineTracing:
    """Test field line tracing with KMAG model."""

    def test_closed_fieldline_dayside(self):
        """Dayside field line at 8 Rs should be closed (both footpoints near surface)."""
        field = SaturnField()
        field_func = saturn_field_wrapper(field, time=284040000.0, coord="KSM")
        trace = trace_fieldline_bidirectional(
            field_func,
            [8.0, 0.0, 0.0],
            step=0.1,
            max_steps=5000,
        )
        # Both endpoints should be near the surface
        assert trace.r[0] < 2.0, f"South footpoint at r={trace.r[0]:.2f}"
        assert trace.r[-1] < 2.0, f"North footpoint at r={trace.r[-1]:.2f}"

    def test_open_fieldline_tail(self):
        """Nightside field line at 30 Rs should be open (extends to max_r)."""
        field = SaturnField()
        field_func = saturn_field_wrapper(field, time=284040000.0, coord="KSM")
        trace = trace_fieldline(
            field_func,
            [-30.0, 0.0, 0.0],
            step=0.2,
            max_steps=5000,
            max_radius=100.0,
        )
        # Should reach either surface or max_radius
        assert trace.r[-1] > 50.0 or trace.r[-1] < 2.0

    def test_field_along_trace_consistent(self):
        """Field magnitude along a trace should vary smoothly."""
        field = SaturnField()
        field_func = saturn_field_wrapper(field, time=284040000.0, coord="KSM")
        trace = trace_fieldline(field_func, [10.0, 0.0, 0.0], step=0.1, max_steps=200)
        # No NaN or inf
        assert np.all(np.isfinite(trace.field_magnitude))
        # Field should be positive everywhere
        assert np.all(trace.field_magnitude > 0)


# ============================================================================
# Performance benchmark
# ============================================================================


class TestPerformance:
    """Benchmark field evaluation performance."""

    def test_field_evaluation_speed(self):
        """With numba JIT, should achieve > 10,000 evals/sec."""
        field = SaturnField()
        # Warm up JIT
        field.field_s3c(10.0, math.pi / 2, 0.0, 284040000.0)

        n_evals = 2000
        start = time_mod.perf_counter()
        for _ in range(n_evals):
            field.field_s3c(10.0, math.pi / 2, 0.0, 284040000.0)
        elapsed = time_mod.perf_counter() - start

        ms_per_eval = elapsed / n_evals * 1000
        evals_per_sec = n_evals / elapsed
        # With numba: expect > 10,000 evals/sec (~0.1 ms each)
        assert evals_per_sec > 10_000, (
            f"Too slow: {ms_per_eval:.3f} ms/eval ({evals_per_sec:.0f} evals/sec)"
        )


# ============================================================================
# make_kmag_field_func — equivalence to field_cartesian
# ============================================================================


class TestMakeKmagFieldFunc:
    """The time-bound field closure must produce the same values as
    SaturnField.field_cartesian, while being significantly faster."""

    def test_equivalence_grid(self):
        """Field values agree to ~1e-10 over a (position, time) grid."""
        from qp.fieldline.kmag_model import make_kmag_field_func

        field = SaturnField()
        rng = np.random.default_rng(42)
        n_pos = 50
        positions = rng.uniform(-25, 25, (n_pos, 3))
        # Skip points too close to the planet (avoid r ~ 0 numerical issues)
        positions = positions[np.linalg.norm(positions, axis=1) > 2.0]
        times = [0.0, 5e7, 1.5e8, 3.0e8, 5.5e8]

        max_abs = 0.0
        max_rel = 0.0
        n_checks = 0
        for t in times:
            f = make_kmag_field_func(field, t, coord="KSM")
            for pos in positions:
                b_new = np.asarray(f(pos))
                b_old = np.asarray(
                    field.field_cartesian(
                        float(pos[0]), float(pos[1]), float(pos[2]), t, coord="KSM"
                    )
                )
                abs_diff = np.max(np.abs(b_new - b_old))
                ref = max(np.max(np.abs(b_old)), 1e-30)
                rel_diff = abs_diff / ref
                max_abs = max(max_abs, abs_diff)
                max_rel = max(max_rel, rel_diff)
                n_checks += 1

        assert max_abs < 1e-9, (
            f"Max abs diff {max_abs:.2e} over {n_checks} evaluations exceeds 1e-9"
        )
        assert max_rel < 1e-10, (
            f"Max rel diff {max_rel:.2e} over {n_checks} evaluations exceeds 1e-10"
        )

    def test_equivalence_known_point(self):
        """Specific test point: agree to machine precision."""
        from qp.fieldline.kmag_model import make_kmag_field_func

        field = SaturnField()
        t = 284040000.0  # ~2009-01-01 in J2000 sec
        pos = np.array([10.0, 5.0, 2.0])

        f = make_kmag_field_func(field, t, coord="KSM")
        b_new = f(pos)
        b_old = field.field_cartesian(10.0, 5.0, 2.0, t, coord="KSM")

        assert_allclose(np.asarray(b_new), np.asarray(b_old), atol=1e-10, rtol=1e-12)

    def test_returns_ndarray(self):
        """Closure must return an ndarray of shape (3,)."""
        from qp.fieldline.kmag_model import make_kmag_field_func

        field = SaturnField()
        f = make_kmag_field_func(field, 0.0, coord="KSM")
        result = f(np.array([10.0, 0.0, 0.0]))
        assert isinstance(result, np.ndarray)
        assert result.shape == (3,)

    def test_non_ksm_falls_back(self):
        """Non-KSM coord systems should fall back to saturn_field_wrapper."""
        from qp.fieldline.kmag_model import make_kmag_field_func

        field = SaturnField()
        # Should not raise — falls back to wrapper
        f = make_kmag_field_func(field, 0.0, coord="S3C")
        result = f(np.array([10.0, 0.0, 0.0]))
        assert result.shape == (3,)

    def test_multiple_positions_same_time(self):
        """Calling the closure many times reuses the precomputed matrices."""
        from qp.fieldline.kmag_model import make_kmag_field_func

        field = SaturnField()
        f = make_kmag_field_func(field, 1e8, coord="KSM")
        # Should not raise across many calls
        for r in np.linspace(3, 25, 20):
            b = f(np.array([r, 0.0, 0.0]))
            assert np.all(np.isfinite(b))
